// A Letter to Tired Parents — Digital Companion
// Content data transcribed from the published book (author's own work).

const SECTIONS = [
  { id: "quick", label: "Quick & Easy", tagline: "For when you have more love than time.", color: "blush" },
  { id: "home", label: "At-Home Adventures", tagline: "Your living room is your oasis.", color: "sage" },
  { id: "frugal", label: "Smart & Frugal", tagline: "Rich experiences, small price tag.", color: "lavender" },
  { id: "sitter", label: "We Got a Sitter!", tagline: "Making every minute count.", color: "blush" },
  { id: "celebrate", label: "Celebrating Us", tagline: "Milestones without the stress.", color: "sage" },
];

const DATES = [
  // ---------------- SECTION 1: QUICK & EASY ----------------
  { id:1, section:"quick", title:"The 3-Question Check-In", vibe:"Intimate, Reflective, Grounding.", time:"15 mins", cost:"$0", energy:"Low", need:"Yourselves. Maybe a drink.", plan:"Sit down, make eye contact, and take turns asking and answering these three questions. No logistics, no kid-talk allowed.\n1) What was a small win for you today?\n2) What's something you're worried about?\n3) What's one thing I can do for you this week?", tip:"Active listening is key. Put your phones away. Just be present.", spark:"What was your favorite part of today, just for you?", hack:"Pop on an episode of Bluey or a read-along audiobook. Tell the kids you have a very important 'meeting' for 15 minutes and cannot be disturbed. They'll love feeling like they're part of a serious plan." },
  { id:2, section:"quick", title:"After-Bedtime Dessert Date", vibe:"Cozy, Indulgent, Quiet.", time:"20 mins", cost:"$ (if you buy it)", energy:"Low", need:"A favorite dessert (ice cream, a piece of fancy chocolate, leftover cake).", plan:"Once the house is quiet, plate the dessert nicely. Sit at the table or on the couch and eat it slowly. Savor it. Talk about anything except the kids.", tip:"Hide a special dessert just for this purpose. The anticipation makes it better.", spark:"If we could teleport to any restaurant in the world for dessert right now, where would we go?" },
  { id:3, section:"quick", title:"Shared Playlist Creation", vibe:"Fun, Collaborative, Nostalgic.", time:"25 mins", cost:"$0", energy:"Medium", need:"A music streaming service (Spotify, Apple Music).", plan:"Open a shared playlist. Set a timer for 10 minutes. Each of you adds 5-7 songs that you're loving right now, or that remind you of each other. Then, listen to the playlist together.", tip:"Name the playlist something fun, like \u201cKitchen Dance Party\u201d or \u201cUs Against the Lunchboxes.\u201d", spark:"What does this song make you feel?" },
  { id:4, section:"quick", title:"The High-Low-Laughter Check-In", vibe:"Grounding, Appreciative, Connected.", time:"10 mins", cost:"$0", energy:"Low", need:"Just the two of you, maybe during bath time for the kids or right after bedtime.", plan:"Quickly share your \u201chigh\u201d (best moment), your \u201clow\u201d (toughest moment), and your \u201claughter\u201d (the funniest or silliest thing that happened) from the last 24 hours.", tip:"This forces you to look for the positive and the humorous, even on a tough day. It\u2019s a perspective-shifter.", spark:"What was a 'small win' you had today that no one else saw?" },
  { id:5, section:"quick", title:"The 5-Minute Tidy-Up Tango", vibe:"Productive, Teamwork, Playful.", time:"5-10 mins", cost:"$0", energy:"Medium", need:"A timer and a messy room (shouldn't be hard to find!).", plan:"Set a timer for 5 minutes. Put on a high-energy song and see how much you can tidy up together before the timer goes off. The goal is speed and fun, not perfection.", tip:"Celebrate with a high-five or a quick kiss when the timer dings. You've conquered the chaos together, even for a moment.", spark:"If we had a whole kid-free day to deep-clean this house, what room would you tackle first?" },
  { id:6, section:"quick", title:"The \u201cSwipe Right\u201d Music Match", vibe:"Fun, Nostalgic, Flirty.", time:"15 mins", cost:"$0", energy:"Low", need:"A music streaming app and two phones.", plan:"Sit back-to-back. One person finds a song and plays a 15-second clip. The other person, without looking, has to \u201cswipe right\u201d (I love this song!) or \u201cswipe left\u201d (Not for me). See how many matches you get!", tip:"This is a great way to discover new music and rediscover old favorites from your partner's collection.", spark:"What does this song remind you of?" },
  { id:7, section:"quick", title:"The 2-Minute Appreciation Burst", vibe:"Loving, Validating, Connected.", time:"2 mins", cost:"$0", energy:"Low", need:"Just your voices.", plan:"Set a timer for 60 seconds each. Take turns listing everything you appreciate about each other, as fast as you can. No overthinking!", tip:"Do this while brushing your teeth or during the bedtime routine. It turns a mundane moment into a connection point.", spark:"Which of my appreciations surprised you the most?" },
  { id:8, section:"quick", title:"The \u201cRemember When\u201d Flashback", vibe:"Nostalgic, Sweet, Intimate.", time:"10 mins", cost:"$0", energy:"Low", need:"Your memories.", plan:"Take turns sharing one specific, happy memory from your early dating days or your wedding. Be as detailed as possible.", tip:"This is a great one to do while cuddling in bed before sleep.", spark:"What's the first thing you noticed about me that day?" },
  { id:9, section:"quick", title:"The Forecast Date", vibe:"Hopeful, Teamwork, Planning.", time:"10 mins", cost:"$0", energy:"Low", need:"Your calendars (phone or physical).", plan:"Over morning coffee, quickly look at the week ahead. Identify one 15-minute slot you can protect for a connection moment.", tip:"This turns vague intentions (\u201cwe should spend time together\u201d) into a concrete plan.", spark:"What's one thing we can look forward to this week?" },
  { id:10, section:"quick", title:"The Compliment Shower", vibe:"Flirty, Appreciative, Uplifting.", time:"5 mins", cost:"$0", energy:"Low", need:"Nothing but your words.", plan:"Stand facing each other. Take turns giving genuine, specific compliments for one minute straight.", tip:"Physical touch (holding hands) during this intensifies the connection.", spark:"Which compliment made you blush?" },
  { id:11, section:"quick", title:"The \u201cWhat If?\u201d Game", vibe:"Imaginative, Playful, Dreamy.", time:"15 mins", cost:"$0", energy:"Low", need:"Your imagination.", plan:"Take turns asking silly or serious \u201cWhat if?\u201d questions. \u201cWhat if we won the lottery tomorrow?\u201d \u201cWhat if we could swap lives with anyone for a day?\u201d", tip:"There are no wrong answers! The goal is to play and dream together.", spark:"What if we had met in high school? Do you think we would have dated?" },
  { id:12, section:"quick", title:"The Silent Smile Challenge", vibe:"Intimate, Funny, Non-Verbal.", time:"3 mins", cost:"$0", energy:"Low", need:"A timer.", plan:"Set a timer for 3 minutes. Look into each other's eyes and try not to talk or laugh. Just smile. See who breaks first.", tip:"This often leads to a fit of giggles, which is a fantastic stress reliever.", spark:"What was going through your head while we were staring?" },
  { id:13, section:"quick", title:"The \u201cTop 3\u201d Download", vibe:"Efficient, Connected, Insightful.", time:"10 mins", cost:"$0", energy:"Low", need:"Nothing.", plan:"Quickly share your top 3 anything: \u201cTop 3 songs I'm loving,\u201d \u201cTop 3 things on my mind,\u201d \u201cTop 3 things I'm grateful for today.\u201d", tip:"This is a great post-work decompression ritual that's more specific than \u201cHow was your day?\u201d", spark:"Which of my top 3s would you like to know more about?" },
  { id:14, section:"quick", title:"The Gratitude Scroll", vibe:"Heartfelt, Intimate, Grounding.", time:"15 mins", cost:"$0", energy:"Low", need:"A single piece of paper and a pen.", plan:"Sit down together and create a \u201cGratitude Scroll.\u201d Take turns writing one sentence each, starting with \u201cI'm grateful for us because...\u201d or \u201cI love our life together when...\u201d. When you're done, read the entire scroll out loud.", tip:"Keep this scroll! You can add to it during future dates, or tuck it away to rediscover later.", spark:"Which line that I wrote surprised you the most?", hack:"Give the kids their own 'Gratitude Mission' \u2014 paper and crayons to quietly draw or write what they're grateful for. You get 15 minutes of quiet, and you can share afterward as a family moment." },
];

const DATES_MORE = {
  quick: ["The 5-Minute Dance Party","Stargazing from the Backyard","Phone Photo Swap","Coffee on the Couch (Before the Chaos)","The Gratitude Gaze","The 'I Saw You' Acknowledgment","The Hand-Hold Walk","The 'No Phone' Coffee Break","The Dreamy Question","The 'One Sentence Story' Game","The Silly Voice Debrief","The 'Thank You' Note"],
  home: ["Themed Trivia Night","Build a Lego Set","Indoor Picnic","Video Game Tournament","Read Aloud Night","Home Documentary Festival","Pillow Fort Ambush","DIY Couples Photo Shoot","Learn a TikTok Dance","Write a Love Letter","Create a Time Capsule","Yoga/Stretching Session","Interior Design Redesign","'Chopped' Pantry Challenge"],
  frugal: ["Park Hopscotch & Swings","Farmers' Market Sampling","Sunset Watch at a Scenic Spot","IKEA Adventure","Coffee Shop Hop","DIY Couples Vision Board","Public Art Walk","Geocaching Adventure"],
  sitter: ["Drive-In Movie","Dessert-Only Crawl","Live Music at a Small Venue","Arcade & Bar","Couples Massage","Sunrise Hike & Breakfast","Antique Store Exploration","Rooftop Bar Views"],
};

// ---------------- SECTION 2: AT-HOME ADVENTURES ----------------
DATES.push(
  { id:15, section:"home", title:"Blanket Fort & Movie Marathon", vibe:"Playful, Nostalgic, Cozy.", time:"2+ hours", cost:"$ (for snacks)", energy:"Medium (setup)", need:"Blankets, pillows, chairs, fairy lights, snacks, a device for movies.", plan:"Build the most epic blanket fort you can. Fill it with pillows and string up some lights. Pick a theme for your marathon (80s classics, cheesy rom-coms, action movies) and dive in.", tip:"Order your favorite takeout and eat it inside the fort. The rule is, you can't leave once you're in!", spark:"What was the best fort you ever built as a kid?", hack:"For a truly uninterrupted night, set up a second, smaller 'kid fort' in their bedroom with their own iPad and snacks. They get their own adventure, and you get yours." },
  { id:16, section:"home", title:"Gourmet Cook-Together Challenge", vibe:"Collaborative, Fun, A Little Fancy.", time:"1.5 hours", cost:"$$ (ingredients)", energy:"Medium/High", need:"A recipe you've never tried, ingredients, music.", plan:"Pick a recipe that looks slightly challenging but fun (homemade pasta, a complex sushi roll, a new dessert). Work as a team \u2014 one on sauce, the other on prep.", tip:"Assign one 'Sous Chef' and one 'Head Chef' to avoid too many cooks. Light candles for the meal.", spark:"If we opened a restaurant, what would we call it and what would be our signature dish?", hack:"Give the kids a 'MasterChef Junior' challenge of their own \u2014 best PB&J or a fruit kabob masterpiece. They're cooking 'with' you, safely out of the way." },
  { id:17, section:"home", title:"DIY Home Spa Night", vibe:"Luxurious, Relaxing, Rejuvenating.", time:"1 hour", cost:"$ (supplies)", energy:"Low", need:"Face masks, lotion, a basin for a foot soak, towels, calming music.", plan:"Transform your bathroom into a spa. Take turns giving each other a hand or foot massage. Put on face masks and just lie down together and breathe.", tip:"Add Epsom salts and a few drops of lavender oil to the foot soak for a truly professional feel.", spark:"Where is the most relaxed you've ever been?" },
  { id:18, section:"home", title:"The MasterChef: Leftovers Edition", vibe:"Creative, Competitive, Fun.", time:"30 mins", cost:"$0", energy:"Medium", need:"The contents of your fridge and pantry.", plan:"You are both chefs in a high-stakes cooking competition. Your secret ingredient? Last night's leftovers! See who can create the most delicious or creative new dish.", tip:"Have a neutral party (an older kid?) be the judge, or just declare it a tie.", spark:"If you could only eat one cuisine for the rest of your life, what would it be?" },
  { id:19, section:"home", title:"Living Room Campout", vibe:"Adventurous, Cozy, Nostalgic.", time:"2+ hours", cost:"$ (snacks)", energy:"Medium (setup)", need:"Blankets, pillows, chairs, a flashlight, campfire snacks (s'mores in the microwave!).", plan:"Build the ultimate blanket fort. Tell \u201cscary\u201d stories (about running out of coffee), share childhood camping memories, or cuddle and watch a movie.", tip:"Use a star projector or fairy lights inside the fort for a magical \u201cstarry night\u201d feel.", spark:"What was your best or worst real camping experience?" },
  { id:20, section:"home", title:"The Blind Taste Test", vibe:"Playful, Surprising, Sensory.", time:"30 mins", cost:"$ (small foods)", energy:"Medium", need:"A blindfold, various small foods (fruits, chocolates, chips, etc.).", plan:"One person is blindfolded. The other feeds them small bites of different foods. The blindfolded person has to guess what they're eating.", tip:"Include something with a unique texture or temperature (like ice cream) to make it more challenging.", spark:"What was the hardest thing to identify? What surprised you?" },
  { id:21, section:"home", title:"The Puzzle Race", vibe:"Competitive, Collaborative, Focused.", time:"1 hour", cost:"$ (a new puzzle)", energy:"Medium", need:"Two identical, small puzzles (100-200 pieces).", plan:"Set a timer and see who can complete their puzzle first! Or work on one large puzzle together against the clock.", tip:"Put on background music and make it a true race. The winner gets a foot rub!", spark:"What's your puzzle strategy? Edges first, or colors?" },
  { id:22, section:"home", title:"The \u201cNo Talk\u201d Board Game", vibe:"Strategic, Funny, Non-Verbal.", time:"45 mins", cost:"$0", energy:"Medium", need:"A classic board game (Checkers, Chess, Jenga).", plan:"Play a full game without speaking. Communicate only through gestures and eye contact.", tip:"This adds a hilarious and intimate new layer to a familiar game.", spark:"What was it like to play without talking? Could you read my moves?" },
  { id:23, section:"home", title:"The Fake Travel Agency", vibe:"Dreamy, Collaborative, Escapist.", time:"1 hour", cost:"$0", energy:"Medium", need:"A laptop or tablet.", plan:"Pick a dream destination. Together, research and plan a full, detailed itinerary as if you were actually going.", tip:"Make it immersive! Find a YouTube walkthrough of your destination city and watch it together.", spark:"If we could only do one thing from this itinerary, what would it be?" },
  { id:24, section:"home", title:"The Karaoke Showdown", vibe:"Energetic, Hilarious, Embarrassing (in a good way!).", time:"1 hour", cost:"$0", energy:"High", need:"A YouTube karaoke channel and a hairbrush microphone.", plan:"Take turns picking songs for each other to perform. Award fake Oscars for \u201cBest Performance,\u201d \u201cMost Dramatic,\u201d etc.", tip:"Embrace the cringe! The worse you are, the more fun it is.", spark:"What song would you absolutely refuse to sing?" },
  { id:25, section:"home", title:"The DIY Cocktail/Mocktail Bar", vibe:"Sophisticated, Creative, Fun.", time:"45 mins", cost:"$$ (ingredients)", energy:"Medium", need:"A few types of juice, soda, fresh fruit, and maybe some spirits.", plan:"Set up a bar with ingredients. Experiment and create your own signature couple's cocktail or mocktail. Give it a fun name.", tip:"Muddle fresh herbs like mint or basil from your garden to feel like a real mixologist.", spark:"If our drink was a person, what would they be like?" },
  { id:26, section:"home", title:"The \u201cSoundtrack of Us\u201d Listening Party", vibe:"Nostalgic, Intimate, Heartfelt.", time:"45 mins", cost:"$0", energy:"Low", need:"Your music streaming service, a speaker.", plan:"Each of you secretly creates a short playlist (3-5 songs) that tells the story of your relationship: your song, your first date, a song that got you through a tough time, a song for the future. Take turns playing your lists and explaining why.", tip:"Don't overthink the song choices! The first ones that come to mind are usually the most meaningful.", spark:"What was it about that specific time in our lives that makes this song so important?", hack:"If the kids are awake, give them headphones with their own playlist for a 'dance party' in the next room while you have yours." }
);

// ---------------- SECTION 3: SMART & FRUGAL ----------------
DATES.push(
  { id:27, section:"frugal", title:"The Supermarket Scavenger Hunt", vibe:"Playful, Surprising, Interactive.", time:"45 mins", cost:"$ (only if you buy things)", energy:"Medium", need:"A list of \u201cscavenger hunt\u201d items.", plan:"Before you go, one person makes a secret list of 10 quirky things to find (\u201cthe ugliest vegetable,\u201d \u201ca product from the 1990s,\u201d \u201can item with a typo,\u201d \u201csomething the other person has never eaten\u201d). Race to find them all!", tip:"The \u201cwinner\u201d gets to pick a favorite snack from the store to enjoy at home.", spark:"What's the weirdest thing you've ever seen someone buy?", hack:"Turn this into a family outing early in the day \u2014 let the kids help find weird items, then revisit the funny moments together after bedtime." },
  { id:28, section:"frugal", title:"The \u201cNo Money\u201d Money Date", vibe:"Dreamy, Forward-Looking, Teamwork.", time:"45 mins", cost:"$0", energy:"Medium", need:"A notepad, pens, and your imaginations.", plan:"Go to a caf\u00e9 or park, get a free water, and dream big. If you had $10,000, $100,000, or $1,000,000, what would you do? This isn't about stress; it's about dreaming together.", tip:"Focus on the \u201cwhy\u201d behind the dreams, not just the number.", spark:"What's one financial goal we could achieve in the next year that would make us both feel amazing?" },
  { id:29, section:"frugal", title:"The \u201cArtist Date\u201d", vibe:"Creative, Quiet, Inspiring.", time:"1 hour", cost:"$ (a cheap sketchbook)", energy:"Low", need:"A sketchbook and a pen/pencil for each of you.", plan:"Go to a park, a museum lobby (often free), or your own backyard. Sit quietly for 20 minutes and draw whatever you see. Then share your \u201cart\u201d without judgment.", tip:"The goal is parallel play and shared quiet focus, not creating a masterpiece.", spark:"What did you notice while you were drawing that you wouldn't have seen otherwise?" },
  { id:30, section:"frugal", title:"The Library Scavenger Hunt", vibe:"Intellectual, Quirky, Adventurous.", time:"1.5 hours", cost:"$0", energy:"Medium", need:"A local library.", plan:"Create a list of quirky books to find: \u201cA book with a blue cover,\u201d \u201cA travel guide to a place we've never heard of,\u201d \u201cA memoir from someone born the same year as us.\u201d", tip:"Check out the books you find and have a reading date later.", spark:"Which of these books are you most curious to read?" },
  { id:31, section:"frugal", title:"The \u201cNo-Spend\u201d Day", vibe:"Resourceful, Adventurous, Challenging.", time:"3+ hours", cost:"$0", energy:"High", need:"A full gas tank and a sense of adventure.", plan:"Plan a half-day outing where you cannot spend a single dollar. Pack a lunch, go for a hike, visit free museums or galleries, window shop.", tip:"The constraint forces creativity and makes you appreciate simple pleasures.", spark:"What was the best free thing we did today?" },
  { id:32, section:"frugal", title:"The Volunteer Date", vibe:"Meaningful, Humbling, Bonding.", time:"2-3 hours", cost:"$0", energy:"Medium/High", need:"A local organization that needs help.", plan:"Sign up to volunteer together at an animal shelter, food bank, or park clean-up.", tip:"Working side-by-side for a cause bigger than yourselves is a powerful way to connect and feel good.", spark:"How did helping others today make you feel about our own life?" },
  { id:33, section:"frugal", title:"The Historical Tour", vibe:"Educational, Interesting, Exploratory.", time:"2 hours", cost:"$0 (or small donation)", energy:"Medium", need:"Your town or a nearby historic area.", plan:"Research a historic walking tour in your city and take it. Read the plaques, admire the architecture, and play tourist in your own town.", tip:"Many cities have free self-guided tour maps available online.", spark:"What's the coolest piece of history we learned today?" },
  { id:34, section:"frugal", title:"The \u201cSkill Swap\u201d Session", vibe:"Playful, Appreciative, Collaborative.", time:"1 hour", cost:"$0", energy:"Medium", need:"A willingness to be a beginner.", plan:"Each of you teaches the other one small, simple skill you're good at that they aren't (a paper airplane, a few phrases in another language, a magic trick, a yoga pose, changing a bike tire). Learning and laughing, not mastery.", tip:"Keep lessons to 15-20 minutes each to stay fun and low-pressure. Celebrate the tiny victories!", spark:"What's something you've always wanted me to teach you?", hack:"Involve the kids in an earlier 'show and tell' session, then practice the skills they 'taught' you on your date \u2014 a built-in conversation starter." }
);

// ---------------- SECTION 4: WE GOT A SITTER! ----------------
DATES.push(
  { id:35, section:"sitter", title:"The Progressive Dinner Crawl", vibe:"Adventurous, Sophisticated, Fun.", time:"3 hours", cost:"$$$", energy:"High", need:"A sitter, a plan, and a ride (or walking shoes).", plan:"Don't commit to one restaurant. Have appetizers at one place, walk to another for the main course, and find a third spot for dessert and drinks.", tip:"Choose spots within walking distance of each other. The change of scenery keeps the conversation fresh.", spark:"If we could do this in any city in the world, which would it be and why?" },
  { id:36, section:"sitter", title:"The Nostalgia Tour", vibe:"Sentimental, Romantic, Fun.", time:"2-3 hours", cost:"$$ (drinks/food)", energy:"Medium", need:"A sitter and a car.", plan:"Visit the spots that defined your early relationship: your first date location, your first apartment, where you got engaged. Share memories at each stop.", tip:"Call ahead to see if your old favorite restaurant or bar is still there. If it is, that's your final destination!", spark:"What was your first impression of me, and how has it changed?" },
  { id:37, section:"sitter", title:"Try Something Actually New", vibe:"Adventurous, Unforgettable, Bonding.", time:"2-3 hours", cost:"$$$ (a class)", energy:"High", need:"A sitter and a reservation.", plan:"Sign up for a one-time beginner's class in something neither of you has tried: axe throwing, pottery, archery, a dance style like salsa, or a new cuisine's cooking class.", tip:"Being beginners together is a huge bonding experience \u2014 you'll be laughing and supporting each other through the clumsiness.", spark:"What was the scariest part of that for you? What was the most fun?" },
  { id:38, section:"sitter", title:"The Silent (Well, Almost) Date", vibe:"Intimate, Observant, Unique.", time:"1.5 hours", cost:"$$ (coffee/lunch)", energy:"Low", need:"A sitter and a notepad/phone for notes.", plan:"Go to a caf\u00e9 or a park. For the first 30 minutes, you are not allowed to talk. Communicate by writing notes instead \u2014 point out things you see, people-watch, share thoughts.", tip:"This forces you to be more observant and intentional with your words. Surprisingly flirty and profound.", spark:"What was that experience like for you? What did you notice?" },
  { id:39, section:"sitter", title:"The Themed Double Date", vibe:"Social, Fun, Themed.", time:"3 hours", cost:"$$$", energy:"High", need:"Another couple and a sitter.", plan:"Plan a double date with a fun theme, like \u201c90s Night\u201d or \u201cTacky Tourist.\u201d Dress the part and choose activities that fit.", tip:"Sharing the silliness with friends amplifies the fun and creates inside jokes.", spark:"What was the most hilarious part of the night?" },
  { id:40, section:"sitter", title:"The Comedy Club Night", vibe:"Hilarious, Lighthearted, Entertaining.", time:"2-3 hours", cost:"$$$", energy:"Medium", need:"A sitter and tickets to a comedy show.", plan:"Find a local comedy club or improv show. Laughter is incredibly bonding and a great way to shake off parental stress.", tip:"Sit in the front if you're feeling brave, or in the back if you want to avoid being called on!", spark:"Which comedian's bit did you relate to the most?" },
  { id:41, section:"sitter", title:"The High-End Hotel Lobby Date", vibe:"Fancy, Sophisticated, Affordable Luxury.", time:"2 hours", cost:"$$ (drinks)", energy:"Low", need:"A sitter and \u201cnice\u201d clothes.", plan:"Go to the fanciest hotel in your city. Order a cocktail or coffee in the lobby lounge and people-watch. It feels luxurious without the price of a room.", tip:"Act like you belong there. Dress up a little to get into the vibe.", spark:"If we were staying here on vacation, what would we do tomorrow?" },
  { id:42, section:"sitter", title:"The Late-Night Diner Adventure", vibe:"Nostalgic, Cozy, Unhurried.", time:"1.5 hours", cost:"$", energy:"Low", need:"A sitter and a 24-hour diner.", plan:"Go to a classic, old-school diner for pie and coffee at 9 PM. There's no rush, and the atmosphere is perfect for long, meandering conversations.", tip:"Sit at the counter for the full authentic experience.", spark:"What's the best late-night food you've ever had?" }
);

// ---------------- SECTION 5: CELEBRATING US ----------------
DATES.push(
  { id:43, section:"celebrate", title:"The \u201cMemory Lane\u201d Anniversary Dinner", vibe:"Deeply Romantic, Nostalgic, Intimate.", time:"3+ hours", cost:"$$$ (nice ingredients)", energy:"Medium", need:"A sitter, ingredients to cook a favorite meal, your wedding playlist.", plan:"Recreate your wedding menu (or your first date's menu) at home. Set the table with your wedding china or fancy dishes. Watch your wedding video or look through your photo album together.", tip:"Write each other a new love letter to read aloud during dessert.", spark:"What's your favorite memory from our wedding day that doesn't involve the photos?" },
  { id:44, section:"celebrate", title:"The \u201cBirthday Scavenger Hunt\u201d", vibe:"Playful, Surprising, Personal.", time:"All day (in bursts)", cost:"$ (small gifts/notes)", energy:"Medium/High (planning)", need:"A sitter (for parts of the day), small notes and gifts.", plan:"Create a scavenger hunt that leads your partner to meaningful spots around your home and neighborhood, with small gifts or loving notes at each stop. The final clue leads to the main gift or activity.", tip:"Incorporate inside jokes and shared memories into the clues \u2014 this makes it incredibly personal.", spark:"Which clue was your favorite to solve?" },
  { id:45, section:"celebrate", title:"The \u201cNew Year, Renewed Us\u201d Retreat", vibe:"Reflective, Hopeful, Goal-Oriented.", time:"2 hours", cost:"$ (a special journal)", energy:"Low", need:"A nice journal, pens, champagne or sparkling cider.", plan:"After the kids are asleep, reflect on the past year \u2014 your highs and lows as a couple and a family. Then write down your hopes, dreams, and goals for the coming year.", tip:"Seal your goals in an envelope to open next New Year's Eve. Make it a new tradition.", spark:"What's one small thing we can do this month to work towards our relationship goal?" },
  { id:46, section:"celebrate", title:"The \u201cAnti-Valentine's\u201d Celebration", vibe:"Cozy, Defiant, Unconventionally Romantic.", time:"2 hours", cost:"$ (takeout)", energy:"Low", need:"Your favorite comfort food, a non-romantic movie (action or comedy!).", plan:"Reject the pressure of Valentine's Day. Order your favorite pizza, wear your comfiest pajamas, and watch a movie with no romantic subplot. Celebrate your real, comfortable, non-Hallmark love.", tip:"Perfect for at-home after the kids are in bed \u2014 a celebration of your authentic, everyday relationship.", spark:"What's something you love about our real, non-perfect life together?" },
  { id:47, section:"celebrate", title:"The \u201cOff-Duty Superhero\u201d Day", vibe:"Appreciative, Pampering, All-About-You.", time:"4+ hours", cost:"$$-$$$", energy:"Low (for the celebrated parent)", need:"A sitter and a plan made by the other partner.", plan:"This day (Mother's/Father's Day) is solely about celebrating the parent, not the family unit. The planning partner organizes a day based entirely on the celebrated parent's interests \u2014 no kids' activities allowed.", tip:"The ultimate gift is true, guilt-free time off. The planning partner handles all logistics without asking for input. End with a quiet, kid-free dinner.", spark:"What part of your day off made you feel the most like 'you'?", hack:"The other partner takes the kids out of the house for several hours \u2014 the park, grandma's, or the movies \u2014 to give the celebrated parent true, precious solitude at home." },
  { id:48, section:"celebrate", title:"The \u201cPhoenix\u201d Celebration", vibe:"Triumphant, Resilient, Hopeful.", time:"2-3 hours", cost:"$$", energy:"Medium", need:"A fire pit (or candles), materials for a time capsule, wine or a favorite drink.", plan:"For surviving a tough year: write down the year's challenges on paper and safely burn them, symbolically releasing them. Then create a \u201cHope Capsule\u201d \u2014 hopes, dreams, and a small memento each \u2014 to open on the same date next year.", tip:"Play music that was uplifting during that tough time. This date acknowledges the struggle while powerfully turning the page.", spark:"What did we learn about ourselves and each other this past year that makes us stronger?" },
  { id:49, section:"celebrate", title:"The \u201cAbundance\u201d Experience", vibe:"Luxurious, Spontaneous, Joyful.", time:"4+ hours", cost:"$$$$", energy:"High", need:"A sitter and a willingness to splurge.", plan:"For a windfall or bonus: do the thing you always say \u201cwe can't justify.\u201d Last-minute show tickets, a couples' massage, a rented convertible to the beach, one night in a luxury hotel in your own city.", tip:"The key is to spend on a memory, not just an item.", spark:"If money were no object for a day, what would our dream 24 hours look like?" },
  { id:50, section:"celebrate", title:"The \u201cSecret Santas\u201d Setup", vibe:"Cozy, Magical, Intimate.", time:"1.5 hours", cost:"$ (snacks)", energy:"Medium", need:"A sitter (or wait until the kids are deeply asleep), holiday decorations, holiday music.", plan:"After the kids are in bed, pour some eggnog or mulled wine, put on your own holiday playlist, and finish decorating the tree together \u2014 the adult decorating session, just the two of you.", tip:"Hang a special \u201cJust Us\u201d ornament that signifies your relationship. Wrap a small, silly gift for each other to open on the spot.", spark:"What's your favorite holiday memory from before we had kids?" }
);

// ---------------- CONVERSATION STARTERS (Tool #2) ----------------
const CONVO_STARTERS = {
  "Fun & Lighthearted": ["If you could have any superhero power for a day, what would it be and why?","What's the funniest thing you saw online this week?","If our life was a movie, what would the title be?"],
  "Dreamy & Future-Focused": ["Where do you see us in 10 years?","What's a new hobby you'd love for us to try together?","If money were no object, what would a perfect Saturday look like for you?"],
  "Intimate & Appreciative": ["What's a small thing I did recently that made you feel loved?","What's your favorite physical feature of mine?","What's a memory of us that always makes you smile?"],
  "Deep & Philosophical": ["What's a fear you're currently facing?","What does 'success' mean to you now, vs. 10 years ago?","What's one thing you're truly proud of yourself for?"],
};
